### ISSUE TITLE
ACT3 Ana Kimberly Hernández Pérez- Cuadro comparativo

### ISSUE THREAD

**Issue by Anakimberly** [SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-Anakimberly#1]
![CUADRO COMPARATIVO](https://user-images.githubusercontent.com/112224202/187833340-934e4099-59d5-4e10-9580-58362a045e34.png)

**Comment by AmeliReyesHernandez** [comment]
15.6 de 20

**Comment by josealfredo79** [comment]
Revisado...
